### ISSUE TITLE
Backup tokens

### ISSUE THREAD

**Issue by willbasky** [encryptedcoins/encoins-frontend#81]
Implement backup of tokens in the cloud.
Backup tokens to [ipfs](https://blockfrost.dev/start-building/ipfs/) with[ Blockfrost API](https://docs.blockfrost.io/#tag/IPFS-Add). More on [hackage](https://hackage.haskell.org/package/blockfrost-api-0.8.1.0/docs/Blockfrost-Types-IPFS.html)
For that user must provide:
1. API key from Blockfrost
2. The cache should be protected by password
3. Checkbox checked.

In case of divergence of the cache union them without deletion. 

Synchronize cache by `refresh` button or automatically (?)
How to retrieve user-specific keys from ipfs?

**Comment by encryptedcoins** [comment]
>  How to retrieve user-specific keys from ipfs?

You can ask Blockfrost to list all pinned files for a particular Blockfrost token. From there, if you can decode (using the password) the file into the set of minting keys, then it's the right file.

**Comment by encryptedcoins** [comment]
Let's sync automatically, adding keys without deletion. Blockfrost currently gives 100 MB of pinned file storage, which is more than enough. Our keys file is from a few bytes to a few KBs in size.

**Comment by encryptedcoins** [comment]
Actually, I think we can allow a quota of 20KB per user file to be used with our Blockfrost key. If this quota is exceeded, we can prompt the user: "The backup storage quota is exceeded. Please enter your Blockfrost key to synchronize the backup."

So, the Blockfrost key can be optional. The password and checkbox are required for the backup to work.

The file ID is normally stored in the browser. If the browser cache is cleared, the user will need to download all the files associated with our Blockfrost key or all the files associated with their key. Then try to decode with the password. If it works, then they have the right file.

**Comment by willbasky** [comment]
The behavior of the interface: 
- The user has entered a password.
- A checkbox for saving to ipfs has appeared in the password window.
- The user checks the box. It is stored in the local cache.
(further description of the state when the password is entered and the checkbox is ticked)
- A unique key for the user is generated.
- It is saved encrypted in the local cache
- And is displayed in the password window
- All valid tokens will be saved in ipfs during further work.
- If the checkbox is not checked or the password is not entered, then nothing will be saved on ipfs
